tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-tertiary-fixed-variant": "#004b73",
        "surface-dim": "#d9dadb",
        "primary": "#80000a",
        "on-background": "#191c1d",
        "inverse-surface": "#2e3132",
        "on-error": "#ffffff",
        "surface-container": "#edeeef",
        "on-secondary-fixed-variant": "#36485b",
        "on-secondary-container": "#526478",
        "on-tertiary-container": "#96cdff",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#d1e4fb",
        "outline-variant": "#e2beba",
        "on-surface": "#191c1d",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#93ccff",
        "surface-variant": "#e1e3e4",
        "on-secondary-fixed": "#091d2e",
        "tertiary": "#004064",
        "inverse-primary": "#ffb4ac",
        "tertiary-container": "#005887",
        "tertiary-fixed": "#cce5ff",
        "surface": "#f8f9fa",
        "primary-fixed": "#ffdad6",
        "primary-fixed-dim": "#ffb4ac",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#cfe2f9",
        "surface-container-high": "#e7e8e9",
        "surface-container-low": "#f3f4f5",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f0f1f2",
        "primary-container": "#a31d1d",
        "surface-tint": "#b22926",
        "surface-bright": "#f8f9fa",
        "surface-container-highest": "#e1e3e4",
        "on-primary-fixed-variant": "#900c12",
        "on-tertiary-fixed": "#001d31",
        "background": "#f8f9fa",
        "on-secondary": "#ffffff",
        "secondary": "#4e6073",
        "on-surface-variant": "#5a413e",
        "on-primary-container": "#ffb6ae",
        "on-primary-fixed": "#410002",
        "secondary-fixed-dim": "#b5c8df",
        "outline": "#8e706d"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "fontFamily": {
        "sans": ["Tajawal", "sans-serif"],
        "headline": ["Plus Jakarta Sans", "Tajawal"],
        "body": ["Work Sans", "Tajawal"],
        "label": ["Work Sans", "Tajawal"]
      }
    },
  },
}
